### ISSUE TITLE
O mundo perfeito: Forms no final de cada post

### ISSUE THREAD

**Issue by cristinebasso** [ellenkorbes/nhoquedafortuna#11]
Mais uma tentativa pra tentar capturar um lead, no final de cada post adicionar um form bem friendly :)

Título: Se você quiser receber as novidades mais quentes do mundo da cozinha deixe seu e-mail aqui
Campos: Nome e email.

**Comment by ellenkorbes** [comment]
http://nhoquedafortuna.com/blog/post/bis/
